[package]
name = "pyro-studio"
version = "0.1.0"
description = "Modern, ultra-fast MariaDB client built with Tauri v2 and React"
authors = ["Pyro Studio Team"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "pyro_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "mysql", "chrono", "bigdecimal", "json"] }
thiserror = "2"
calamine = "0.26"
rust_xlsxwriter = { version = "0.80", features = ["constant_memory"] }
chrono = { version = "0.4", features = ["serde"] }
rfd = "0.17.2"
dirs = "7.0.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "gzip"] }
base64 = "0.22"
futures-util = "0.3"
aes-gcm = "0.11.1"
getrandom = "0.4.3"
tauri-plugin-single-instance = "2.5.2"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "unwind"
strip = true
